FROM php:8.3-fpm
RUN echo "access.log = /dev/null" >> /usr/local/etc/php-fpm.d/www.conf
RUN docker-php-ext-install mysqli
#RUN sed -i 's|deb.debian.org|archive.debian.org|g' /etc/apt/sources.list
#RUN sed -i 's|security.debian.org|archive.debian.org|g' /etc/apt/sources.list
#RUN sed -i '/stretch-updates/d' /etc/apt/sources.list
#RUN apt-get update && apt-get install vim -y
COPY DigiCertGlobalRootCA.crt.pem /etc/ssl/certs/DigiCertGlobalRootCA.crt.pem
COPY ./src /var/www/html